project:
  type: book
execute:
  cache: true
  freeze: auto
book:
  favicon: cover.png
  google-analytics: "G-5T7SZYQV79"
  title: "R4PDE.net"
  subtitle: "R for Plant Disease Epidemiology"
  author: "Emerson M. Del Ponte"
  date: 10/23/2023
  date-format: long
  image: cover.png
  publisher: "Emerson M. Del Ponte"
  license: "CC BY-NC"
  sidebar:
    search: true
    style: floating
    collapse-level: 1
    border: true
  repo-url: https://github.com/emdelponte/epidemiology-R
  cover-image: cover.png
  downloads: [epub, docx] 
  repo-actions: [edit, issue]
  sharing: [twitter, linkedin]
  page-footer: 
    border: false
    background: light
    left: | 
      R4PDE - R for Plant Disease Epidemiology is written by Emerson Del Ponte
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
    
  chapters:
    - index.qmd
    - cite.qmd
    - author.qmd
    - acknowledgements.qmd
    - intro.qmd
    - part: "Epidemic data"
      chapters:
        - data-terminology.qmd
        - data-ordinal.qmd
        - data-actual-severity.qmd
        - data-accuracy.qmd
        - data-sads.qmd
        - data-training.qmd
        - data-remote-sensing.qmd
        
        
    - part: "Temporal analysis"
      chapters: 
        - temporal-dpc.qmd
        - temporal-models.qmd
        - temporal-fitting.qmd
    - part: "Spatial analysis"
      chapters:
        - spatial-gradients.qmd
        - spatial-models.qmd
        - spatial-fitting.qmd
        - spatial-patterns.qmd
        - spatial-tests.qmd
    - part: "Epidemics and yield"
      chapters:
        - yieldloss-concepts.qmd
        - yieldloss-regression-models.qmd
    - part: "Disease prediction"
      chapters: 
        - warning-systems.qmd
    - references.qmd


bibliography: references.bib
csl: phytopathology.csl
prefer-html: true
format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: 
        - flatly
        - r4pd.scss
        #- custom.scss
      dark: 
        - darkly
  epub:
    epub-cover-image: cover.png
    toc: true
  docx:
    reference-doc: custom-reference.docx
    toc: true
    number-sections: true
    highlight-style: github